[profile.default]
# Run tests in parallel with optimal thread count
test-threads = "num-cpus"

# Retry flaky tests up to 2 times
retries = 2

# Timeout for individual tests (30 seconds)
slow-timeout = "30s"

# Show test output for failed tests immediately
failure-output = "immediate"
