codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 3  # Wait for multiple OS builds

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        
comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "target/"
  - "*.toml"
  - "build.rs"

github_checks:
  annotations: true
